[workspace]
resolver = "2"
members = [
    "node",
    "pallets/template",
    "runtime",
    "store", 
    "crypto", 
    "network", 
    "mempool", 
    "consensus"
]
[profile.release]
panic = "unwind"



[patch.crates-io]
finality-grandpa = { path = "./finality-grandpa" }
