[workspace]
resolver = "2"
members = [
    "node",
    "pallets/template",
    "runtime",
    "store", 
    "crypto", 
    "network", 
    "mempool", 
    "consensus",
    "hotstuff"
]
[profile.release]
panic = "unwind"
