[package]
name = "store"
version = "0.1.0"
authors = ["Alberto Sonnino <alberto@sonnino.com>"]
edition = "2021"
publish = false

[dependencies]
rocksdb = "0.21.0"
tokio = { version = "1.3.0", features = ["sync", "macros", "rt"] }